select distinct h.PatientPK,
SiteCode, 
FacilityName,
'IQCare' as Emr,
'Kenya HMIS II' as Project,
p.HTSID as HtsNumber,
HTSEncounterId as EncounterId,
VisitDate as TestDate,
TestedBefore as EverTestedForHiv,
WhenLastTested as MonthsSinceLastTest,
ClientTestedAs,
TestEntryPoint as EntryPoint,
StrategyHTS as TestStrategy,
FinalTestOneResult as TestResult1,
FinalResultTestTwo as TestResult2,
finalResultHTS as FinalTestResult,
FinalResultsGiven as PatientGivenResult,
TBScreeningHTS as TbScreening,
clientSelfTestesd as ClientSelfTested,
CoupleDiscordant,
TestType,
case when Consent='1' or Consent='Yes' then 'Yes' else 'No' end as Consent from  tmp_HTS_LAB_register h inner join tmp_PatientMaster p
on h.PatientPK=p.PatientPK