SELECT '' AS PatientID,
       '' AS PatientPK,
       '' AS SiteCode,
	   '' AS FacilityID,
       'Kenya EMR' AS EMR,
       'Kenya HMIS II' AS Project,
       NOW() AS VisitDate,
       '' AS AdverseEventRegimen,
       '' AS AdverseEvent,
       '' AS AdverseEventCause,
       '' AS Severity,
       '' AS AdverseEventActionTaken,
       '' AS AdverseEventClinicalOutcome,
	   NOW() AS AdverseEventStartDate,
       NOW() AS AdverseEventEndDate,
       '' AS AdverseEventIsPregnant